"""initial schema

Revision ID: 1d6c2762d036
Revises:
Create Date: 2026-06-22 20:12:10.001798
"""

from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1d6c2762d036"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before the items.embedding column (ADR 0014).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "prompts",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("analyzer", "evaluator", name="prompt_role"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_index(
        "idx_prompts_one_active",
        "prompts",
        ["name"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "source_health",
        sa.Column(
            "source",
            sa.Enum("jobtech", "riksdagen", "entsoe", name="source_kind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("healthy", "paused", name="source_status"),
            server_default=sa.text("'healthy'"),
            nullable=False,
        ),
        sa.Column("drift_detail", sa.Text(), nullable=True),
        sa.Column(
            "last_checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="user_role"),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_actor_time",
        "audit_log",
        ["actor_user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "notification_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "dashboard", "email", "webhook", name="notification_channel"
            ),
            nullable=False,
        ),
        sa.Column(
            "frequency",
            sa.Enum("instant", "daily_digest", name="notification_frequency"),
            server_default=sa.text("'instant'"),
            nullable=False,
        ),
        sa.Column("destination", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "channel"),
    )
    op.create_table(
        "usage_counters",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "run_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "window_start"),
    )
    op.create_table(
        "watches",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("jobtech", "riksdagen", "entsoe", name="source_kind"),
            nullable=False,
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column(
            "schedule_interval",
            sa.Interval(),
            server_default=sa.text("'1 hour'"),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_watches_due",
        "watches",
        ["next_run_at"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "idx_watches_user_active",
        "watches",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running", "succeeded", "failed", "paused", name="run_status"
            ),
            server_default=sa.text("'running'"),
            nullable=False,
        ),
        sa.Column("langsmith_trace_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["watch_id"], ["watches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_runs_one_active",
        "pipeline_runs",
        ["watch_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_index(
        "idx_runs_watch",
        "pipeline_runs",
        ["watch_id", sa.literal_column("started_at DESC")],
        unique=False,
    )
    op.create_table(
        "cost_events",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column(
            "model",
            sa.Enum("ollama", "claude", name="model_kind"),
            nullable=False,
        ),
        sa.Column(
            "tokens_in",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "tokens_out",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cost_user_time",
        "cost_events",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "items",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("watch_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("jobtech", "riksdagen", "entsoe", name="source_kind"),
            nullable=False,
        ),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768),
            nullable=True,
        ),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["pipeline_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["watch_id"], ["watches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "content_hash"),
    )
    op.create_index(
        "idx_items_watch",
        "items",
        ["watch_id", sa.literal_column("fetched_at DESC")],
        unique=False,
    )
    op.create_table(
        "analyses",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=True),
        sa.Column(
            "model_used",
            sa.Enum("ollama", "claude", name="model_kind"),
            nullable=False,
        ),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("confidence", sa.REAL(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["prompt_id"], ["prompts.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_analyses_item", "analyses", ["item_id"], unique=False)
    op.create_table(
        "evaluations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("analysis_id", sa.UUID(), nullable=False),
        sa.Column("relevance_score", sa.REAL(), nullable=False),
        sa.Column("confidence", sa.REAL(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("approved", "review", name="eval_status"),
            nullable=False,
        ),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["analyses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id"),
    )
    op.create_table(
        "notifications",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "dashboard", "email", "webhook", name="notification_channel"
            ),
            server_default=sa.text("'dashboard'"),
            nullable=False,
        ),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="notification_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["analyses.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedup_key"),
    )
    op.create_index(
        "idx_notifications_user",
        "notifications",
        ["user_id", sa.literal_column("delivered_at DESC")],
        unique=False,
    )
    op.create_table(
        "review_decisions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "approved", "rejected", "corrected", name="review_decision"
            ),
            nullable=False,
        ),
        sa.Column("corrected_label", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_decisions")
    op.drop_index("idx_notifications_user", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("evaluations")
    op.drop_index("idx_analyses_item", table_name="analyses")
    op.drop_table("analyses")
    op.drop_index("idx_items_watch", table_name="items")
    op.drop_table("items")
    op.drop_index("idx_cost_user_time", table_name="cost_events")
    op.drop_table("cost_events")
    op.drop_index("idx_runs_watch", table_name="pipeline_runs")
    op.drop_index(
        "idx_runs_one_active",
        table_name="pipeline_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_table("pipeline_runs")
    op.drop_index(
        "idx_watches_user_active",
        table_name="watches",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(
        "idx_watches_due",
        table_name="watches",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("watches")
    op.drop_table("usage_counters")
    op.drop_table("notification_settings")
    op.drop_index("idx_audit_actor_time", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("source_health")
    op.drop_index(
        "idx_prompts_one_active",
        table_name="prompts",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("prompts")
    # ### end Alembic commands ###
    for enum_name in (
        "source_kind",
        "source_status",
        "run_status",
        "model_kind",
        "eval_status",
        "notification_status",
        "user_role",
        "prompt_role",
        "review_decision",
        "notification_channel",
        "notification_frequency",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    op.execute("DROP EXTENSION IF EXISTS vector")
