"""SQLAlchemy ORM models — the canonical data model.

Mirrors docs/data-model.md. Column server-defaults are written so an
Alembic autogenerate produces the same DDL documented there.
"""

import datetime
import uuid

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Interval,
    Numeric,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy import (
    Enum as SAEnum,
)
from sqlalchemy.dialects.postgresql import JSONB, REAL, UUID
from sqlalchemy.orm import Mapped, mapped_column

from pulsegraph.db.base import Base
from pulsegraph.domain import enums
from pulsegraph.domain.constants import EMBEDDING_DIM

# --- column helpers ---


def _pk() -> Mapped[uuid.UUID]:
    """A UUID primary key generated by the database."""
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def _created_at() -> Mapped[datetime.datetime]:
    """A creation timestamp defaulting to now()."""
    return mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )


def _enum(cls: type, name: str) -> SAEnum:
    """A native PostgreSQL enum using the members' string values."""
    return SAEnum(
        cls,
        name=name,
        values_callable=lambda e: [m.value for m in e],
    )


# --- tables ---


class User(Base):
    """A tenant account (ADR 0005/0021)."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = _pk()
    email: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[enums.UserRole] = mapped_column(
        _enum(enums.UserRole, "user_role"),
        nullable=False,
        server_default=text("'user'"),
    )
    # When the user granted consent / lawful basis for processing, recorded
    # at signup (GDPR, ADR 0018). Nullable so pre-existing accounts (created
    # before consent was captured) read as null rather than a false value.
    consented_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True)
    )
    created_at: Mapped[datetime.datetime] = _created_at()


class Watch(Base):
    """A user's standing query against one source (ADR 0005/0015)."""

    __tablename__ = "watches"
    __table_args__ = (
        Index(
            "idx_watches_user_active",
            "user_id",
            postgresql_where=text("is_active"),
        ),
        Index(
            "idx_watches_due",
            "next_run_at",
            postgresql_where=text("is_active"),
        ),
    )

    id: Mapped[uuid.UUID] = _pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    source: Mapped[enums.SourceKind] = mapped_column(
        _enum(enums.SourceKind, "source_kind"), nullable=False
    )
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    config: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    is_active: Mapped[bool] = mapped_column(
        nullable=False, server_default=text("true")
    )
    schedule_interval: Mapped[datetime.timedelta] = mapped_column(
        Interval, nullable=False, server_default=text("'1 hour'")
    )
    last_run_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True)
    )
    next_run_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    created_at: Mapped[datetime.datetime] = _created_at()
    updated_at: Mapped[datetime.datetime] = _created_at()


class SourceHealth(Base):
    """Global per-source drift state (ADR 0010)."""

    __tablename__ = "source_health"

    source: Mapped[enums.SourceKind] = mapped_column(
        _enum(enums.SourceKind, "source_kind"), primary_key=True
    )
    status: Mapped[enums.SourceStatus] = mapped_column(
        _enum(enums.SourceStatus, "source_status"),
        nullable=False,
        server_default=text("'healthy'"),
    )
    drift_detail: Mapped[str | None] = mapped_column(Text)
    last_checked_at: Mapped[datetime.datetime] = _created_at()


class PipelineRun(Base):
    """One execution of the graph for one watch (ADR 0007/0015)."""

    __tablename__ = "pipeline_runs"
    __table_args__ = (
        Index(
            "idx_runs_watch",
            "watch_id",
            text("started_at DESC"),
        ),
        Index(
            "idx_runs_one_active",
            "watch_id",
            unique=True,
            postgresql_where=text("status = 'running'"),
        ),
    )

    id: Mapped[uuid.UUID] = _pk()
    watch_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("watches.id", ondelete="CASCADE"), nullable=False
    )
    status: Mapped[enums.RunStatus] = mapped_column(
        _enum(enums.RunStatus, "run_status"),
        nullable=False,
        server_default=text("'running'"),
    )
    langsmith_trace_id: Mapped[str | None] = mapped_column(Text)
    error: Mapped[str | None] = mapped_column(Text)
    started_at: Mapped[datetime.datetime] = _created_at()
    finished_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True)
    )


class Prompt(Base):
    """A versioned prompt in the registry (ADR 0011)."""

    __tablename__ = "prompts"
    __table_args__ = (
        UniqueConstraint("name", "version"),
        Index(
            "idx_prompts_one_active",
            "name",
            unique=True,
            postgresql_where=text("is_active"),
        ),
    )

    id: Mapped[uuid.UUID] = _pk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    role: Mapped[enums.PromptRole] = mapped_column(
        _enum(enums.PromptRole, "prompt_role"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    template: Mapped[str] = mapped_column(Text, nullable=False)
    is_active: Mapped[bool] = mapped_column(
        nullable=False, server_default=text("false")
    )
    created_at: Mapped[datetime.datetime] = _created_at()


class Item(Base):
    """A fetched unit of content with its embedding (ADR 0003/0014)."""

    __tablename__ = "items"
    __table_args__ = (
        UniqueConstraint("user_id", "content_hash"),
        Index(
            "idx_items_watch",
            "watch_id",
            text("fetched_at DESC"),
        ),
    )

    id: Mapped[uuid.UUID] = _pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    watch_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("watches.id", ondelete="CASCADE"), nullable=False
    )
    run_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("pipeline_runs.id", ondelete="SET NULL")
    )
    source: Mapped[enums.SourceKind] = mapped_column(
        _enum(enums.SourceKind, "source_kind"), nullable=False
    )
    external_id: Mapped[str | None] = mapped_column(Text)
    raw_payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    content_hash: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[list[float] | None] = mapped_column(
        Vector(EMBEDDING_DIM)
    )
    embedding_model: Mapped[str | None] = mapped_column(Text)
    fetched_at: Mapped[datetime.datetime] = _created_at()


class Analysis(Base):
    """The Analyzer's output and its provenance (ADR 0002/0011)."""

    __tablename__ = "analyses"
    __table_args__ = (Index("idx_analyses_item", "item_id"),)

    id: Mapped[uuid.UUID] = _pk()
    item_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("items.id", ondelete="CASCADE"), nullable=False
    )
    prompt_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("prompts.id", ondelete="SET NULL")
    )
    model_used: Mapped[enums.ModelKind] = mapped_column(
        _enum(enums.ModelKind, "model_kind"), nullable=False
    )
    model_version: Mapped[str] = mapped_column(Text, nullable=False)
    params: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    result: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float] = mapped_column(REAL, nullable=False)
    created_at: Mapped[datetime.datetime] = _created_at()


class Evaluation(Base):
    """The Evaluator's grade of an analysis (ADR 0006)."""

    __tablename__ = "evaluations"

    id: Mapped[uuid.UUID] = _pk()
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("analyses.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    relevance_score: Mapped[float] = mapped_column(REAL, nullable=False)
    confidence: Mapped[float] = mapped_column(REAL, nullable=False)
    status: Mapped[enums.EvalStatus] = mapped_column(
        _enum(enums.EvalStatus, "eval_status"), nullable=False
    )
    evaluated_at: Mapped[datetime.datetime] = _created_at()


class ReviewDecision(Base):
    """A human verdict from the review queue (ADR 0012)."""

    __tablename__ = "review_decisions"

    id: Mapped[uuid.UUID] = _pk()
    evaluation_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("evaluations.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    reviewer_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    decision: Mapped[enums.ReviewDecision] = mapped_column(
        _enum(enums.ReviewDecision, "review_decision"),
        nullable=False,
    )
    corrected_label: Mapped[str | None] = mapped_column(Text)
    note: Mapped[str | None] = mapped_column(Text)
    decided_at: Mapped[datetime.datetime] = _created_at()


class Notification(Base):
    """A delivered (or pending) notification (ADR 0003/0016)."""

    __tablename__ = "notifications"
    __table_args__ = (
        UniqueConstraint("user_id", "dedup_key"),
        Index(
            "idx_notifications_user",
            "user_id",
            text("delivered_at DESC"),
        ),
    )

    id: Mapped[uuid.UUID] = _pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    analysis_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("analyses.id", ondelete="CASCADE"), nullable=False
    )
    channel: Mapped[enums.NotificationChannel] = mapped_column(
        _enum(enums.NotificationChannel, "notification_channel"),
        nullable=False,
        server_default=text("'dashboard'"),
    )
    dedup_key: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[enums.NotificationStatus] = mapped_column(
        _enum(enums.NotificationStatus, "notification_status"),
        nullable=False,
        server_default=text("'pending'"),
    )
    delivered_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=True)
    )
    # Digest delivery retry count (ADR 0016). Incremented each time a
    # daily-digest push fails for this row; once it reaches
    # Settings.digest_max_attempts the row is dead-lettered (status set to
    # FAILED) instead of being retried forever. Unused for instant/
    # dashboard delivery, which never leaves a row PENDING.
    attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )


class NotificationSetting(Base):
    """Per-user, per-channel delivery preferences (ADR 0016)."""

    __tablename__ = "notification_settings"

    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
    )
    channel: Mapped[enums.NotificationChannel] = mapped_column(
        _enum(enums.NotificationChannel, "notification_channel"),
        primary_key=True,
    )
    frequency: Mapped[enums.NotificationFrequency] = mapped_column(
        _enum(enums.NotificationFrequency, "notification_frequency"),
        nullable=False,
        server_default=text("'instant'"),
    )
    destination: Mapped[str | None] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(
        nullable=False, server_default=text("true")
    )


class CostEvent(Base):
    """A per-call token and cost ledger entry (ADR 0008)."""

    __tablename__ = "cost_events"
    __table_args__ = (
        Index(
            "idx_cost_user_time",
            "user_id",
            text("created_at DESC"),
        ),
    )

    id: Mapped[uuid.UUID] = _pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    run_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("pipeline_runs.id", ondelete="SET NULL")
    )
    model: Mapped[enums.ModelKind] = mapped_column(
        _enum(enums.ModelKind, "model_kind"), nullable=False
    )
    tokens_in: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    tokens_out: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    cost_usd: Mapped[float] = mapped_column(
        Numeric(10, 6), nullable=False, server_default=text("0")
    )
    created_at: Mapped[datetime.datetime] = _created_at()


class AuditLogEntry(Base):
    """A security-relevant user/account action (ADR 0021)."""

    __tablename__ = "audit_log"
    __table_args__ = (
        Index(
            "idx_audit_actor_time",
            "actor_user_id",
            text("created_at DESC"),
        ),
    )

    id: Mapped[uuid.UUID] = _pk()
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL")
    )
    action: Mapped[str] = mapped_column(Text, nullable=False)
    entity_type: Mapped[str] = mapped_column(Text, nullable=False)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    # Mapped to column "metadata"; the attribute is renamed because
    # `metadata` is reserved on the declarative Base.
    meta: Mapped[dict] = mapped_column(
        "metadata",
        JSONB,
        nullable=False,
        server_default=text("'{}'::jsonb"),
    )
    created_at: Mapped[datetime.datetime] = _created_at()
